### ISSUE TITLE
Reading ppt file doen'st work

### ISSUE THREAD

**Issue by jacobnijgh** [PHPOffice/PHPPowerPoint#103]
I can't load in a ppt file, i used the following syntax:
http://stackoverflow.com/questions/29190556/can-phppowerpoint-copy-existing-powerpoint

This is the exception 
Invalid file format for PhpOffice\PhpPowerpoint\Reader\Serialized:

Is this already available in v0.3 or only in dev branch yet?
Thanks in advance

**Comment by Progi1984** [comment]
The PowerPoint97 reader is available in the version 0.3.

https://github.com/PHPOffice/PHPPowerPoint/releases/tag/0.3.0

If you have problem with it, give us a file example and open an issue, please.
