### ISSUE TITLE
Change width of cell

### ISSUE THREAD

**Issue by dami95** [PHPOffice/PHPPowerPoint#104]
Is any possible to change width of cell in table?

![zrzut ekranu 2015-06-15 o 17 35 37](https://cloud.githubusercontent.com/assets/724522/8163683/f9f55a00-1384-11e5-8bea-cccca794bf8d.png)

**Comment by Progi1984** [comment]
@dami95 I just added the documentation.

http://phppowerpoint.readthedocs.org/en/develop/shapes_table.html#define-the-width-of-a-cell

**Comment by dami95** [comment]
Thank you :)

**Comment by Progi1984** [comment]
@dami95 No, you must define all or any.

**Comment by Progi1984** [comment]
@dami95 Ok for you ?

**Comment by dami95** [comment]
Yes, it's working. Thank you!
