### ISSUE TITLE
Some charts improvments

### ISSUE THREAD

**Issue by dami95** [PHPOffice/PHPPowerPoint#105]
I need some new things to use in my project, it's any possible to implement it?
1) Maximum value of axis (e.g. 100) - screen 1
2) Additional right axis - screen 1
3) stacked bar - screen 2

![zrzut ekranu 2015-06-15 o 17 41 10](https://cloud.githubusercontent.com/assets/724522/8163835/bfaa8e0a-1385-11e5-8a84-789ce5c8dced.png)
![zrzut ekranu 2015-06-15 o 17 41 57](https://cloud.githubusercontent.com/assets/724522/8163874/fab2f21c-1385-11e5-93b9-4f5328abf89d.png)

**Comment by dami95** [comment]
@Progi1984 Now It's any possible to display percent values on axis chart?

**Comment by Progi1984** [comment]
@dami95 I don't believe it's in the library.

**Comment by jrking4** [comment]
@dami95 I added a pull request for a grouping option on bar charts.  This would give you the stacked percentage you are looking for.

**Comment by dami95** [comment]
I will check it, thanks!

**Comment by Progi1984** [comment]
@dami95 Could you give us a sample file with the chart in your first screen ?

I need to work on this file. Thanks.

**Comment by Progi1984** [comment]
@dami95 For the third point, the documentation is done about the @jrking4 implementation : http://phppowerpoint.readthedocs.org/en/develop/shapes_chart.html#stacking

**Comment by dami95** [comment]
@Progi1984 screens come from SVG charts. 
Do you need this in PPT?

**Comment by Progi1984** [comment]
@dami95 Yes, please.

**Comment by Progi1984** [comment]
@dami95 Some news ?

**Comment by dami95** [comment]
Hm... I can't see that setting in PPTX...

**Comment by Progi1984** [comment]
So first and second points are not available in PowerPoint ?

**Comment by dami95** [comment]
Yep :/

**Comment by Progi1984** [comment]
@dami95 I close it, so. If you find the way for enabling two first points, I will be ok for implementing these in PHPPowerpoint.

**Comment by raghavzwt06** [comment]
Can be possible this type of Stacked and Grouped column chart ?
![screenshot_1](https://user-images.githubusercontent.com/20964161/38546177-96095070-3cc9-11e8-8a59-4fde429060f4.png)

**Comment by Progi1984** [comment]
@raghavzwt06 Have you got a sample file ?
