### ISSUE TITLE
Chart Options Not Working As Expected

### ISSUE THREAD

**Issue by jrking4** [PHPOffice/PHPPowerPoint#107]
When creating a chart a few items are not working properly. I am experiencing these when saving as a PPT2007.
~~-Chart Series - Fill Color has no effect. Always defaults to default blue color~~
~~-Chart Series - setShowPercentage function has no effect. It always shows count regardless of setting~~
-Chart Title - Chart title is always visible. calling "$shape->getTitle()->setVisible( false )" has no effect.
-Chart Title also defaults to Series name in single series bar chart.

**Comment by jrking4** [comment]
I fixed the two Chart Series bugs with my PR. The chart title bugs, I never got a chance to debug and troubleshoot.

**Comment by Progi1984** [comment]
@jrking4 So the first two bugs are ok with the develop branch ?

Could you give two sample code (the most simplest) for the two last bugs ? And a screenshot of the expected rendering ? Thanks

**Comment by Progi1984** [comment]
@jrking4 The third point seems to be fixed in develop branch. Could you confirm ? 

I think that fixes the 4rd issue. Could you test it ? Else could you give us a sample code and a screenshot of the actual & expected rendering ?

**Comment by Progi1984** [comment]
@jrking4 Some news ?

**Comment by jrking4** [comment]
Looks like the issue is fixed in the latest branch.  Thanks :+1:

**Comment by Progi1984** [comment]
@jrking4 Cool...
