### ISSUE TITLE
How can I convert ppt to html

### ISSUE THREAD

**Issue by imredcat** [PHPOffice/PHPPowerPoint#109]
Title is all!!
I need more example. T^T

**Comment by Progi1984** [comment]
@imredcat At the moment, there is no way.

You can read a PPT with PowerPoint97 Reader. But there is not HTML Writer.

**Comment by imredcat** [comment]
I understand this library is cannot convert ppt to html code.
I ask more.
Can I get text of PPT contents?
Can I display PPT contents on web browser? after read ppt file.

**Comment by Progi1984** [comment]
@imredcat You can browse your PPT.

You can [get all slides](http://phpoffice.github.io/PHPPowerPoint/docs/develop/classes/PhpOffice.PhpPowerpoint.PhpPowerpoint.html#method_getAllSlides). And for each slide, you can [get all shapes](http://phpoffice.github.io/PHPPowerPoint/docs/develop/classes/PhpOffice.PhpPowerpoint.Slide.html#method_getShapeCollection).

After that, for each one, you can get all styles (width, height, fill, border), and data (text, images).
