### ISSUE TITLE
Load error with ppt file.

### ISSUE THREAD

**Issue by imredcat** [PHPOffice/PHPPowerPoint#110]
This is my code but get error.
> require_once('/home/user/widget/ppp/Autoloader.php');
> \PhpOffice\PhpPowerpoint\Autoloader::register();
> $oReaderPPT = \PhpOffice\PhpPowerpoint\IOFactory::createReader('PowerPoint97');
> $pptfile = '/home/user/upload/title.ppt';
> $pptfile = '/home/user/upload/title.pptx';
> $r = $oReaderPPT->load($pptfile);

ERROR : 
> Invalid file format for PhpOffice\PhpPowerpoint\Reader\Serialized: /home/user/upload/title.ppt.

So I changed Shared/OLERead.php to Common/src/Common/Microsoft/OLERead.php
I get error such follow
> File PowerPoint 97 in error (Location : RTSlide > perSlideHFContainer > RT_HeadersFooters).
> PowerPoint97.phpLINE : 762

How Can I load ppt(x) files?
Please give my the way! TT
I use 0.3.0 version and requirement check is all passed, 
php ver 5.3

**Comment by Progi1984** [comment]
@imredcat 

For reading PPT files,

```php
require_once('/home/user/widget/ppp/Autoloader.php');
\PhpOffice\PhpPowerpoint\Autoloader::register();
$oReaderPPT = \PhpOffice\PhpPowerpoint\IOFactory::createReader('PowerPoint97');
$pptfile = '/home/user/upload/title.ppt';
$r = $oReaderPPT->load($pptfile);
```

If you have errors for reading your PPT file, could you send us ?

For reading PPTX files,
there is no reader for the moment : it's on the pipe (#44).

**Comment by imredcat** [comment]
Ok Thank you.
How can I send the ppt file to you?

**Comment by Progi1984** [comment]
@imredcat Dropbox, or any file sharing systems

**Comment by imredcat** [comment]
@Progi1984 
Here the ppt file.
https://www.dropbox.com/s/8cwnxb1eid7lh8b/test.ppt?dl=0
Please fix it.

**Comment by Progi1984** [comment]
@imredcat Fixed in the develop branch ;)
