### ISSUE TITLE
Getting Started example doesn't work...

### ISSUE THREAD

**Issue by zanj2006** [PHPOffice/PHPPowerPoint#114]
Hi,

the example on page https://github.com/PHPOffice/PHPPowerPoint doesn't work... Still getting error like this:
**Fatal error: Class 'PhpPowerpoint' not found in C:\projects\i\p\vendor\phpoffice\phppowerpoint\index.php on line 5**

When I add name space prefix for: **$objPHPPowerPoint = new PhpPowerpoint();** like 
**$objPHPPowerPoint = new \PhpOffice\PhpPowerpoint\PhpPowerpoint();**

I'll get another errors... 
**Fatal error: Class 'Alignment' not found in C:\projects\i\p\vendor\phpoffice\phppowerpoint\index.php on line 28**

Please help... I can't go further... Please can you update your example to be working? Or what should be done, to make it working...

Thanks, Jirka

**Comment by Progi1984** [comment]
@zanj2006 Have you included PHPPowerPoint source with composer or manually : http://phppowerpoint.readthedocs.org/en/master/installing.html#installation ?

**Comment by zanj2006** [comment]
With composer...
IMHO there is a problem with autoloader or some misuse of namespace (missing USE keyword)

**Comment by Progi1984** [comment]
Which version do you use ?
* dev-master
* dev-develop
* 0.4.0
* 0.2.0

Reference : https://packagist.org/packages/phpoffice/phppowerpoint

**Comment by zanj2006** [comment]
0.4.0

For instalation I used composer.json:

{
    "require": {
       "phpoffice/phppowerpoint": "dev-master"
    }
}

index.php:
<?php
require_once 'src/PhpPowerpoint/Autoloader.php';
\PhpOffice\PhpPowerpoint\Autoloader::register();

$objPHPPowerPoint = new PhpPowerpoint();

// Create slide
$currentSlide = $objPHPPowerPoint->getActiveSlide();
...

**Comment by Progi1984** [comment]
@zanj2006 If you use composer, you need to include its autoloader and no, the autoloader of PhpPowerpoint.

**Comment by zanj2006** [comment]
So now solved... There were two points...

1. Composer Autoloader was needed to incorporate - but it was not enough...
2. Aliasing of used Classes is at least as important... So making your example to be working I had to add after the autoload:

<?php
require_once 'vendor/autoload.php';

use PhpOffice\PhpPowerpoint\PhpPowerpoint;
use PhpOffice\PhpPowerpoint\IOFactory;
use PhpOffice\PhpPowerpoint\Style\Color;
use PhpOffice\PhpPowerpoint\Style\Alignment;

$objPHPPowerPoint = new PhpPowerpoint(); // without USE aliasing can't find the class file...

Thank for your help...

**Comment by Progi1984** [comment]
@zanj2006 Thank you for your feedback. I just fixed the sample in Readme with your feedback in 98b9a3b0216fbe8cc5f67935b6e9b472f958c527.

**Comment by justijndepover** [comment]
You should probably fix your site as well. The example given is wrong. It took me quite some time to figure out it wasn't working.
http://phppresentation.readthedocs.io/en/latest/general.html

**Comment by rizqyfahmi** [comment]
Hi guys, 
I'm trying to embed pptx file to my website using PHPPresentation library but I have not found how to do it yet. I only found how to read tree of pptx in the samples folder. can help me please?
