### ISSUE TITLE
Reader for PowerPoint2007

### ISSUE THREAD

**Issue by arbabi2010** [PHPOffice/PHPPowerPoint#44]
Hi. I want to  set document properties for an exiting file ... I know how i can set properties but i can't load a existing file ... i asked about like this in phpword and i can load but for powerpoint i can't load something like that.
please help me. thanks a lot

**Comment by Progi1984** [comment]
@arbabi2010 A reader for PowerPoint 2007 has been added and it is available in develop branch. Could you test it ?

**Comment by Progi1984** [comment]
@arbabi2010 No news. I close the issue.
