### ISSUE TITLE
How to add link to image?

### ISSUE THREAD

**Issue by dvdtth** [PHPOffice/PHPPowerPoint#49]
Taking the following code from the samples folder:

````php
$currentSlide = $objPHPPowerPoint->getActiveSlide();
$shape = $currentSlide->createDrawingShape();
$shape->setName('PHPPowerPoint logo')
      ->setDescription('PHPPowerPoint logo')
      ->setPath('./resources/phppowerpoint_logo.gif')
      ->setHeight(36)
      ->setOffsetX(10)
      ->setOffsetY(10);
$shape->getShadow()->setVisible(true)
                   ->setDirection(45)
                   ->setDistance(10);
```

Adding the following line to add a hyperlink to the image doesn't seem to work.

```php
$shape->getHyperlink()->setUrl('https://github.com/PHPOffice/PHPPowerPoint/')
                      ->setTooltip('PHPPowerPoint');
```

**Comment by Progi1984** [comment]
Some members in @PHPOffice/phppowerpoint-team or @PHPOffice/phpword-team  for testing with a PowerPoint, please ? Thanks

**Comment by JewrassicPark** [comment]
Hyperlink to image works for me for powerpoint 2007 with code like above but does not work for me for text

**Comment by Progi1984** [comment]
@JewrassicPark Could you give us some code, please ?

**Comment by JewrassicPark** [comment]
Both RichTextShape and individual text elements can have a hyperlink set on them but the hyperlink insert via xml is only implemented for individual elements 

so I was doing 
$shape = $currentSlide->createRichTextShape();
$shape->getHyperLink()->setUrl($args['l'])->setTooltip($args['l']);

and instead I should have been doing 
$shape = $currentSlide->createRichTextShape();
$textRun = $shape->createTextRun($args['t']);
$textRun->getHyperLink()->setUrl($args['l'])->setTooltip($args['l']);

**Comment by JewrassicPark** [comment]
Modifying the writeShapeText function of the Powerpoint2007 Slide writer allows you to set the url for a shape instead of just individual text elements (which I find more useful because it omits hyperlink style) 

my code:
```
    private function writeShapeText(XMLWriter $objWriter, RichText $shape, $shapeId)
    {
        // p:sp
        $objWriter->startElement('p:sp');

        // p:nvSpPr
        $objWriter->startElement('p:nvSpPr');

        // p:cNvPr
        $objWriter->startElement('p:cNvPr');
        $objWriter->writeAttribute('id', $shapeId);
        $objWriter->writeAttribute('name', '');
		
		//write hyperlink
		if ($shape->hasHyperlink()) {
            $this->writeHyperlink($objWriter, $shape);
        }
		
        $objWriter->endElement();
```

**Comment by Progi1984** [comment]
@JewrassicPark Just add your code with some unit tests and that works perfectly. Thanks.

PS : If you want, you can pull request your improvements ;)

**Comment by Progi1984** [comment]
@JewrassicPark Some news ?

**Comment by JewrassicPark** [comment]
Works for me in dev branch

**Comment by Ashishkumar1** [comment]
how can i add image through hyperlink in phpoffice presentation

**Comment by JewrassicPark** [comment]
@Ashishkumar1  

This is my code to add an image to the current slide: 

```

//$args is an array with information about the shape

$currentSlide = $this->pp->getActiveSlide();
$shape = $currentSlide->createDrawingShape();
$shape->setResizeProportional(false)->setWidth($args['w'])->setHeight($args['h']);
$shape->setName($args['n'])
	  ->setDescription($args['d'])
	  ->setOffsetX($args['x'])
	  ->setOffsetY($args['y'])
	  ->setPath($args['p'],false);
if($args['l']){  // if we want to link the image
	$shape->getHyperLink()->setUrl($args['l'])->setTooltip($args['l']);
}	
```

**Comment by Progi1984** [comment]
Thanks @JewrassicPark for the support :)
