### ISSUE TITLE
Feature not implemented (l.1131 : 102)

### ISSUE THREAD

**Issue by gmuehl** [PHPOffice/PHPPowerPoint#60]
Some strange Problems over here. When opening a ppt with 

$pptreader = PhpOffice\PhpPowerpoint\IOFactory::createReader('PowerPoint97');

it tells me "Unknown File Format". So i have opened the File in LibreOffice and saved it as PowerPoint97 because saving in Office makes no difference. After that this Exception shows up:

```
Feature not implemented (l.1131 : 102)
```

so, what is the meaning of these numbers? ;)

**Comment by gmuehl** [comment]
Mail is sent

**Comment by Progi1984** [comment]
@gmuehl Question : Have you embed PPTX file or any object in your file PPT file ? Your file seems not a valid PPT file.

**Comment by gmuehl** [comment]
At first i came to the same conclusion, though - the PPT consists of simple Text and Images, nothing more. When i open it in Powerpoint there are no Error Messages. Just change the Text, save it, and try to open it with PHPPowerpoint again -> same Error message, possible Errors are not Removed on Save. The only working solution so far is the following:

- go to Cloudconvert and convert the File to ODP
- go to Cloiudconvert and convert the ODP back to PPT

though - because the Conversion on Cloudconvert is possible, and the file can be loaded in Powerpoint i guess that the format is valid (somehow).

**Comment by Progi1984** [comment]
@gmuehl It's weird.

With the original file, I have some errors in reading with OffVis :
![image](https://cloud.githubusercontent.com/assets/1533248/5720888/bed23998-9b2a-11e4-8058-a9719d0469f0.png)

With the original file saved in LibreOffice, I have no errors :
![image](https://cloud.githubusercontent.com/assets/1533248/5720890/c8d97c30-9b2a-11e4-8581-5f4d8114844c.png)

What's your file generator ? Which version ?

**Comment by gmuehl** [comment]
Office 2010, i've allready told the User to update his Powerpoints, though - he has the same Problem that there are no changes on saving the File (even when edited);

![schnappschuss_011315_021135_pm](https://cloud.githubusercontent.com/assets/151238/5721159/55826400-9b2e-11e4-9d5d-2c828bf8d54c.jpg)

i've tried the LibreOffice-Trick a few weeks ago, that resulted in the same error, only CloudConvert worked for me

**Comment by Progi1984** [comment]
@gmuehl Do you save the file or save as a new file ?

**Comment by Progi1984** [comment]
@gmuehl Could you test with the last version of the develop branch ?

**Comment by gmuehl** [comment]
Sure, will check the Branch tomorrow

**Comment by gmuehl** [comment]
Very interestung, dev-master delivers the following Error:

    Fatal error: Uncaught exception 'Exception' with message 'Invalid file format for PhpOffice\PhpPowerpoint\Reader\Serialized:

Same File with the Development-Branch can be read, but not parsed:

    Fatal error: Uncaught exception 'Exception' with message 'File PowerPoint 97 in error (Location : RTSlide > drawing > OfficeArtDg > groupShape > rgfb).' in 
    /vendor/phpoffice/phppowerpoint/src/PhpPowerpoint/Reader/PowerPoint97.php:822

**Comment by Progi1984** [comment]
@gmuehl I have the same error.

It's because your file is bad formatted in the PowerPoint format. 
Could you try [this procedure](https://support.office.microsoft.com/en-us/article/Determine-whether-a-PowerPoint-2010-presentation-is-compatible-with-PowerPoint-2003-or-earlier-388b0be3-4c12-4248-89f5-377b22efc533) on the client's computer with his file ?

**Comment by Progi1984** [comment]
@gmuehl Some news ?

**Comment by Progi1984** [comment]
@gmuehl Need your help for fixing this bug.

**Comment by gmuehl** [comment]
The File was ok, though, the Customer cancelled the Job because it lasted too long

**Comment by Progi1984** [comment]
Thanks @gmuehl
