### ISSUE TITLE
Support of notes slide

### ISSUE THREAD

**Issue by dung1764** [PHPOffice/PHPPowerPoint#63]
Is it possible to add notes/comments for each slide ?

**Comment by JewrassicPark** [comment]
I changed the writeNote function of my Slide writer for Powerpoint2007 and this works for me:

    public function writeNote(Note $pNote = null)
    {
        // Check slide
        if (is_null($pNote)) {
            throw new \Exception("Invalid \PhpOffice\PhpPowerpoint\Slide\Note object passed.");
        }

        // Create XML writer
        $objWriter = $this->getXMLWriter();

        // XML header
        $objWriter->startDocument('1.0', 'UTF-8', 'yes');

        // p:notes
        $objWriter->startElement('p:notes');
        $objWriter->writeAttribute('xmlns:a', 'http://schemas.openxmlformats.org/drawingml/2006/main');
        $objWriter->writeAttribute('xmlns:p', 'http://schemas.openxmlformats.org/presentationml/2006/main');
        $objWriter->writeAttribute('xmlns:r', 'http://schemas.openxmlformats.org/officeDocument/2006/relationships');

        // p:cSld
        $objWriter->startElement('p:cSld');

        // p:spTree
        $objWriter->startElement('p:spTree');

        // p:nvGrpSpPr
        $objWriter->startElement('p:nvGrpSpPr');

        // p:cNvPr
        $objWriter->startElement('p:cNvPr');
        $objWriter->writeAttribute('id', '1');
        $objWriter->writeAttribute('name', '');
        $objWriter->endElement();

        // p:cNvGrpSpPr
        $objWriter->writeElement('p:cNvGrpSpPr', null);

        // p:nvPr
        $objWriter->writeElement('p:nvPr',null);
        
     
        
        // ## p:nvGrpSpPr
        $objWriter->endElement();

        // p:grpSpPr
        $objWriter->startElement('p:grpSpPr');

        // a:xfrm
        $objWriter->startElement('a:xfrm');

        // a:off
        $objWriter->startElement('a:off');
        $objWriter->writeAttribute('x', SharedDrawing::pixelsToEmu($pNote->getOffsetX()));
        $objWriter->writeAttribute('y', SharedDrawing::pixelsToEmu($pNote->getOffsetY()));
        $objWriter->endElement(); // a:off

        // a:ext
        $objWriter->startElement('a:ext');
        $objWriter->writeAttribute('cx', SharedDrawing::pixelsToEmu($pNote->getExtentX()));
        $objWriter->writeAttribute('cy', SharedDrawing::pixelsToEmu($pNote->getExtentY()));
        $objWriter->endElement(); // a:ext

        // a:chOff
        $objWriter->startElement('a:chOff');
        $objWriter->writeAttribute('x', SharedDrawing::pixelsToEmu($pNote->getOffsetX()));
        $objWriter->writeAttribute('y', SharedDrawing::pixelsToEmu($pNote->getOffsetY()));
        $objWriter->endElement(); // a:chOff

        // a:chExt
        $objWriter->startElement('a:chExt');
        $objWriter->writeAttribute('cx', SharedDrawing::pixelsToEmu($pNote->getExtentX()));
        $objWriter->writeAttribute('cy', SharedDrawing::pixelsToEmu($pNote->getExtentY()));
        $objWriter->endElement(); // a:chExt

        // ## a:xfrm
        $objWriter->endElement();

        // ## p:grpSpPr
        $objWriter->endElement();


		$objWriter->startElement('p:sp');
		$objWriter->startElement('p:nvSpPr');
		
		$objWriter->startElement('p:cNvPr');
		$objWriter->writeAttribute('id','1');
		$objWriter->writeAttribute('name','Notes Placeholder');
		$objWriter->endElement(); //p:cNvPr
		
		$objWriter->startElement('p:cNvSpPr');
		
		$objWriter->startElement('a:spLocks');
		$objWriter->writeAttribute('noGrp','1');
		$objWriter->endElement();//a:spLocks
		
		$objWriter->endElement(); //p:cNvSpPr
			
		$objWriter->startElement('p:nvPr');
		
		$objWriter->startElement('p:ph');
		$objWriter->writeAttribute('type','body');
		$objWriter->writeAttribute('idx','1');
		$objWriter->endElement(); //p:ph
		
		$objWriter->endElement();//p:nvPr
		
		$objWriter->endElement();//p:nvSpPr
		
		$objWriter->writeElement('p:spPr',null);
	
	
		$objWriter->startElement('p:txBody');
		$objWriter->writeElement('a:bodyPr',null);
		$objWriter->writeElement('a:lstStyle',null);
		
        // Loop shapes
        $shapes  = $pNote->getShapeCollection();
        foreach ($shapes as $shape) {
            // Check type
            if ($shape instanceof RichText) {
			   $paragraphs = $shape->getParagraphs();
			   $this->writeParagraphs($objWriter, $paragraphs);
            }
        }
		
		$objWriter->endElement();//p:txBody
		//p:sp
		$objWriter->endElement();
		
		//p:spTree
        $objWriter->endElement();
		//p:cSld
        $objWriter->endElement();

        // > p:notes
        $objWriter->endElement();

        // Return
        return $objWriter->getData();
    }

**Comment by Progi1984** [comment]
@JewrassicPark @dung1764 If you could test with the last version of the develop branch, and give some feedback (success & fail), I could close or continue this issue. Thanks.

**Comment by JewrassicPark** [comment]
Works for me, but to be fair it's the code I already checked so it's not a great test.

**Comment by Progi1984** [comment]
I finally tested on my Windows Computer with PowerPoint & PowerPoint online and it works. So I close this issue.

**Comment by JewrassicPark** [comment]
I've found a case in which it causes powerpoint to crash and it's not
trivial

If you create a first slide without notes then make subsequent slides with
notes, powerpoint can't read the file. I'm currently looking into the bug.

**Comment by JewrassicPark** [comment]
the relationship is either with the _rels directory in notesslides or the
notemaster but I couldn't find the exact relationship

right now I've just patched my project by adding a placeholder note for
slides that don't have notes but this isnt a good solution and should be
opened as a bug
