### ISSUE TITLE
Disapearing space

### ISSUE THREAD

**Issue by skwi** [PHPOffice/PHPPowerPoint#65]
I have an issue that happens randomly (at least is how it looks to me). I can not reporduce it but my users see it regularly.

When I open a PPTX and saves it back, some spaces in text are disapearing.

For example : 
```xml
<a:r>
    <a:rPr b="1" dirty="0" err="1" lang="fr-FR" smtClean="0" sz="1600"/>
    <a:t>Adengo</a:t>
</a:r>
<a:r>
    <a:rPr b="1" dirty="0" lang="fr-FR" smtClean="0" sz="1600"/>
    <a:t>est </a:t>
</a:r>
<a:r>
    <a:rPr b="1" dirty="0" lang="fr-FR" sz="1600"/>
    <a:t>utilisable sur tous </a:t>
</a:r>
```
becomes
```xml
<a:r>
    <a:rPr b="1" lang="fr-FR" smtClean="0" sz="1600"/>
    <a:t>Adengoest</a:t>
</a:r>
<a:r>
    <a:rPr b="1" dirty="0" lang="fr-FR" smtClean="0" sz="1600"/>
    <a:t/>
</a:r>
<a:r>
    <a:rPr b="1" dirty="0" lang="fr-FR" sz="1600"/>
    <a:t>utilisable sur tous </a:t>
</a:r>
```

I can't find a pattern leading to this bug.

Any idea why I see it ?
Is there something to do in Powerpoint to prevent it ? (Userers on my website are willing to do some simple manipulation in PowerPoint if this error can be avoided)

or is this a real bug ?

**Comment by skwi** [comment]
Sorry for the late answer.
I did not made any modification to PHPPowerPoint.
I have looked in detail to this "err" attribute and it means that there is a spelling error on the word.
I don't have enough data to see if there is a correlation between the bug and this attribute.

**Comment by Progi1984** [comment]
@skwi Could you test with the latest version of the develop branch ?

You first code is the XML generated by PHPPowerPoint ?

**Comment by skwi** [comment]
After updating to the latest version and further investigation, the bug was due to an incorrect regex manipulating data before using PHPPowerPoint to manipulate the document.

Anyway thanks for your help, updating to the latest version gave us better tools to find the problem.
