### ISSUE TITLE
Namespace error on charts with PHPExcel

### ISSUE THREAD

**Issue by omadsen** [PHPOffice/PHPPowerPoint#67]
I cannot get presentations with slides containing charts with spreadsheets to work. I think the references to PHPExcel in  Writer\PowerPoint2007\Chart.php not will comply with the PHPExcel autoloader, unless there is a backslash in the beginning?

**Comment by buliq** [comment]
Hi.
Without the backslash it throws: 

Warning: include_once(PhpOffice/PhpPowerpoint/Writer/PowerPoint2007/PHPExcel/Cell.php): failed to open stream: No such file or directory in /var/www/xxx/library/Zend/Loader.php on line 146

Using ZF1 I could not fake it to be in this namespace

**Comment by Progi1984** [comment]
Fixed in f7c07c2.
