### ISSUE TITLE
Shadow does not work on RichTextShapes anymore

### ISSUE THREAD

**Issue by nynka** [PHPOffice/PHPPowerPoint#81]
Setting the shadow on RichTextShapes seems to have no effect anymore.

Consider this:
```php
$shape = $this->createRichTextShape();
$shape->setHeight(30)->setWidth(60)->setOffsetX((960-60)-20)->setOffsetY(720-30-20);
$shape->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_RIGHT );
$shape->getActiveParagraph()->getAlignment()->setVertical( Alignment::VERTICAL_BOTTOM );
// Has no effect
$shape->getShadow()->setVisible(true)->setAlpha(75)->setBlurRadius(2)->setDirection(45);

$textRun = $shape->createTextRun('PhpPowerpoint');
$textRun->getFont()->setBold(true)->setSize(12)->setColor( new Color( 'FFFFFFFF' ) );
```
This used to work in previous versions, please look into it.

**Comment by Progi1984** [comment]
I work on it...

**Comment by Progi1984** [comment]
@nynka Fixed in develop branch. Could you test it and give us your feedback ? (Sample 11 is a sample with RichText and shadow)

**Comment by Progi1984** [comment]
@nynka Ok for you ?

**Comment by nynka** [comment]
I'll check and get back to you. Thanks!
Den 26 jun 2015 13:12 skrev "Progi1984" <notifications@github.com>:

**Comment by Progi1984** [comment]
@nynka Thanks :)

**Comment by nynka** [comment]
@Progi1984 It seems like we're getting shadow on all texts now.

**Comment by Progi1984** [comment]
@nynka That should be fixed... Could you test again ?

**Comment by nynka** [comment]
@Progi1984 Yup it's working fine now. Thanks! :)

**Comment by Progi1984** [comment]
@nynka Thanks ;)
