### ISSUE TITLE
New features need to add in charts.

### ISSUE THREAD

**Issue by manikrds** [PHPOffice/PHPPowerPoint#82]
Hi Everyone,

Can we implement chart like this ?

![graph](https://cloud.githubusercontent.com/assets/10435483/5676221/f6d77956-97f7-11e4-8544-c2e76e5baab1.jpg)

**Comment by manikrds** [comment]
Column chart also 

Hi,

Is that possible to have column chart like this ?? (Not 3D bar chart)

![2d_bar_chart](https://cloud.githubusercontent.com/assets/10435483/5856848/bc8152de-a26c-11e4-9908-1c0e2031f895.jpg)

**Comment by Progi1984** [comment]
@manikrds : Just added in the develop branch.
