### ISSUE TITLE
PPTX Files Not Recognized on iOS

### ISSUE THREAD

**Issue by nekrozon** [PHPOffice/PHPPowerPoint#86]
The PPTX file format should open on IOS natively in safari.

When PPTX files generated in PHPPowerPoint on iOS 8.1.3, the following error appears:

Unable to Read Document

The file format is invalid.

**Comment by Progi1984** [comment]
@nekrozon Have you tested with the develop branch ?

**Comment by nekrozon** [comment]
Yep I'm using the develop branch so that I could get fill to work for text/slide backgrounds.

I will double check though.

**Comment by Progi1984** [comment]
@nekrozon Could you give us some feedback from your double check ? Thanks

**Comment by Progi1984** [comment]
@nekrozon PHPPowerPoint 0.4.0 has been released. I would like to solve your issue for 0.5.0. Could you answer to my question ?

**Comment by nekrozon** [comment]
Sure what's your question?

**Comment by Progi1984** [comment]
@nekrozon Have you got always the problem with the develop branch for PPTX files on iOS ?

**Comment by nekrozon** [comment]
When I came across your project and tested it did not work. I developed my own solution following a different route. Thanks!!

**Comment by Progi1984** [comment]
Okay. Thanks. Bye.
