### ISSUE TITLE
add methods to DocumentLayout

### ISSUE THREAD

**Issue by maraky** [PHPOffice/PHPPowerPoint#87]
Hi!
I propose to add methods to DocumentLayout, return the size of the slide in px, as the height, the width of the object and its displacement is set in px. This will avoid unnecessary conversions and make the code more readable.
Thanks, Alexander

**Comment by Progi1984** [comment]
@maraky I just added units management in DocumentLayout.

You can get and set width and height in differents units (pixels, emu, cm, mm, pt and inches).

This is available in the develop branch.
