### ISSUE TITLE
 Fatal error: Class 'PhpPowerpoint' not found in ....

### ISSUE THREAD

**Issue by lepoulp** [PHPOffice/PHPPowerPoint#88]
Hi,

i've tried installing the latest version on my XAMPP (PHP 5.5), sample works but it includes the sample_header.php etc.. which i don't use in my test.

When i try to replicate a simple test, it fails at this point :(
$objPHPPowerPoint = new PhpPowerpoint();
With this error : Fatal error: Class 'PhpPowerpoint' not found in ...
if finds the required files and i haven't changed the class name so i don't see why i'm getting this error :(

require_once 'src/PhpPowerpoint/Autoloader.php';
\PhpOffice\PhpPowerpoint\Autoloader::register();

$objPHPPowerPoint = new PhpPowerpoint();

// Create slide
$currentSlide = $objPHPPowerPoint->getActiveSlide();

// Create a shape (drawing)
$shape = $currentSlide->createDrawingShape();
$shape->setName('PHPPowerPoint logo')
      ->setDescription('PHPPowerPoint logo')
      ->setPath('./resources/phppowerpoint_logo.gif')
      ->setHeight(36)
      ->setOffsetX(10)
      ->setOffsetY(10);
$shape->getShadow()->setVisible(true)
                   ->setDirection(45)
                   ->setDistance(10);

// Create a shape (text)
$shape = $currentSlide->createRichTextShape()
      ->setHeight(300)
      ->setWidth(600)
      ->setOffsetX(170)
      ->setOffsetY(180);
$shape->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_CENTER );
$textRun = $shape->createTextRun('Thank you for using PHPPowerPoint!');
$textRun->getFont()->setBold(true)
                   ->setSize(60)
                   ->setColor( new Color( 'FFE06B20' ) );

$oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');
$oWriterPPTX->save(__DIR__ . "/sample.pptx");
$oWriterODP = IOFactory::createWriter($objPHPPowerPoint, 'ODPresentation');
$oWriterODP->save(__DIR__ . "/sample.odp");

**Comment by JewrassicPark** [comment]
I had some issues getting the examples to work too. It took me awhile to get the autoloader to work the way I wanted it to.  Here's the start of my file: 
```
use PhpOffice\PhpPowerpoint\PhpPowerpoint;
use PhpOffice\PhpPowerpoint\IOFactory;
use PhpOffice\PhpPowerpoint\Style\Alignment;
use PhpOffice\PhpPowerpoint\Style\Color;
use PhpOffice\PhpPowerpoint\Shape\MemoryDrawing;
use PhpOffice\PhpPowerpoint\Style\Fill;

require_once $root.'/src/PhpPowerpoint/Autoloader.php';
\PhpOffice\PhpPowerpoint\Autoloader::register();

```

**Comment by lepoulp** [comment]
Thanks a lot it worked !

**Comment by youssefboudaya** [comment]
i installed phppresentation package in my 5.4 laravel application and tried a simple example i get this error "Class 'PhpOffice\PhpPresentation\PhpPresentation' not found" How can i fix it ?
