### ISSUE TITLE
Can we create Gantt chart?

### ISSUE THREAD

**Issue by sarjeet-singh** [PHPOffice/PHPPowerPoint#97]
Hi Team,

Can we create gantt chart with this library?

If yes then you can give a example for this.
Or 
If  no then we can give this feature in library.

Please help me on this

Thanks
Sarjeet Singh

**Comment by Progi1984** [comment]
hi @sarjeet-singh ,

PowerPoint doesn't support gantt chart, so PHPPowerPoint won't do it.

So if you need it, you can [generate a Gantt Chart as an image](http://jpgraph.net/download/manuals/chunkhtml/ch16s04.html) and use the generated image in PowerPoint.
