### ISSUE TITLE
is it possible to create a bar chart that's wider than it is tall?

### ISSUE THREAD

**Issue by Stephen-Hazel** [PHPOffice/PHPPowerPoint#99]
Take your sample "Sample_07_Chart.php"
scoot to line 71 where you're setting the chart's width, height, etc.

Change the height to 300, width to 900, x to 5, y to 5

The thing plots into a teeny square.

An easy fix for ya, hopefully?

**Comment by Stephen-Hazel** [comment]
Hmmm, it looks like whatever that resizeProportional junk is doing, it's WRECKING stuff.  I kinda wish whoever put that in would take it out and not mess around like that...

**Comment by Stephen-Hazel** [comment]
well, I got around the problem.  Wrote my own bar chart drawing php that does EVERYthing in terms of images (1 pixel images scaled to a bar), text and lines.  So now I don't even need the built in chart stuff that doesn't work.  Reinventing the wheel strikes again !!

**Comment by Stephen-Hazel** [comment]
Actually, this is gonna be a GREAT way to get graphs around in our dang company.  Everybody's got powerpoint, it can print beautifully (unlike trying to SQUEEZE your webpage onto a printer - YUCK), and people can email it around.  And it's extremely difficult to just copy/paste to excel and maintain local (CRAPPY) copies of the data that never update.  This library is fricken GREAT - you have saved my life (from my boss).

**Comment by Progi1984** [comment]
@Stephen-Hazel Finally your problem is solved ?

**Comment by Stephen-Hazel** [comment]
Sorry, I kinda gave up on that route.
I'm just using phppowerpoint as kind of a "canvas" that I can put dot, lines and images on.
I have slightly better graphing functionality now (that doesn't follow the API phppp has).
So I think I'll just close that out?
Hopefully that's ok?

**Comment by Progi1984** [comment]
@Stephen-Hazel Thanks for your answer. Don't hesitate to add a pull request for improving the API and add/correct functionnality. I'm open to discuss.
